### ISSUE TITLE
better connection handling

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#1]
I would like to add the following:

* Support for no API_KEY (useful for non-submitting use, i.e, GETs)
* Support for arbitrary instance name (i.e, DCC uses *.demo.encodedcc.org)

I have a PR for this, I will fix the tests and submit it.

**Comment by hitz** [comment]
I have a PR for this but ... I probably should have forked as I don't have permission to push here.
Let me know if you want to give me permission or if I should fork and PR from there.

**Comment by nathankw** [comment]
I've added you as a collaborator. I think for large changes we'll have to set up some formal review process, but for simpler changes should be fine.

**Comment by nathankw** [comment]
So feel free to push it and I'll look over it using the diff report.

**Comment by nathankw** [comment]
Merged in PR from Ben.
