### ISSUE TITLE
Adding remove option in addition to patch and post

### ISSUE THREAD

**Issue by gabdank** [StanfordBioinformatics/encode_utils#11]
Sometimes you need to remove a property from the schema. For example, biosample schema property "pooled_from" is optional. If it is present it has to contain at least two entries, otherwise, it should not be in the schema. So if you want to take a biosample and remove "pooled_from" you can not just submit empty list - dependency will cause the schema validation to fail.

To allow removal of properties you can use requests.put() function.
If you get the object from the portal specifying in the URL "?frame=edit" you can remove from the returned dictionary properties you want to get rid of, and then use this modified dictionary for requests.put call.

The one that is using requests.put  should do it cautiously, making sure the accession, uuid, schema_version are not overwritten when the requests.put is used.

**Comment by nathankw** [comment]
This feature has been added in release [1.3.0](https://github.com/StanfordBioinformatics/encode_utils/blob/master/README.md). 
Please see example at http://encode-utils.readthedocs.io/en/latest/examples.html#removing-properties-from-a-record.

**Comment by nathankw** [comment]
Hey @gabdank , wanted to check if you had a chance to try this.  Can I close the issue?

**Comment by nathankw** [comment]
Closing, please reopen if any issues.
