### ISSUE TITLE
getting "upload creds" from existing files

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#13]
This case is VERY niche but I found myself wanting to get just the S3 bucket key ("path") for an already uploaded file.   connection.get_upload_credentials doesn't work.

I want to GET (not post) to /file/ENCFF000AAA.bam/upload).

This should return a JSON with the current creds.  Probably this is a DCC only matter use case.

**Comment by nathankw** [comment]
Fixed in release 1.5.2.
