### ISSUE TITLE
low level connection.get() should have datastore=elasticsearch option

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#14]
I get for submission you want to have gets -> datastore=database but for most GET functions you are going to want to use the elasticsearch option (which is the default, no datastore query parameter).

it's currently hardcoded:
https://github.com/StanfordBioinformatics/encode_utils/blob/master/encode_utils/connection.py#L520

**Comment by nathankw** [comment]
I'll need to add another arg to ``connection.Connection()`` that will allow one to indicate whether the API is being used for submission, in which case ``connection.Connection.get()`` will set `datastore=database`, otherwise won't set it all all.

**Comment by nathankw** [comment]
This is implemented now in master. Will be in next release.  Now when used for submitting, folks will need to instantiate with ``Connection(submission=True)``, which ``eu_register.py``already does.
