### ISSUE TITLE
test can't find datafile

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#3]
I will try to fix this one too, but:

> ======================================================================
> ERROR: test_before_file_post (encode_utils.tests.test_connection.TestConnection)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/hitz/Documents/workspace/encode_utils/encode_utils/tests/test_connection.py", line 39, in test_before_file_post
>     res = self.conn.before_post_file(payload)
>   File "/Users/hitz/Documents/workspace/encode_utils/encode_utils/connection.py", line 601, in before_post_file
>     md5sum = euu.calculate_md5sum(file_name)
>   File "/Users/hitz/Documents/workspace/encode_utils/encode_utils/utils.py", line 42, in calculate_md5sum
>     with open(file_path,'rb') as fh:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/test_fq_40recs.fastq.gz'
> 
> 

this is if you run the tests from github checkout directory using the command:
`
 python3 -m unittest encode_utils/tests/test_connection.py 
`

Not sure in what directory I should be running them...

**Comment by nathankw** [comment]
Bug noted. I need to fix the path to the data file in that one specific test so that you can run the test from other places. For now you can run the tests within the tests directory.

**Comment by hitz** [comment]
but then it can't import encode_utils

**Comment by hitz** [comment]
I have a fix now.

**Comment by nathankw** [comment]
Fixed in branch iss3, now merged in.
