### ISSUE TITLE
[eu_register.py] Dry run mode not working when dcc_mode is taken from environment variable

### ISSUE THREAD

**Issue by emi80** [StanfordBioinformatics/encode_utils#44]
The `dry_run` command line argument is not passed when initializing the `Connection` object if the `dcc_mode` command line argument is not specified (see [this line](https://github.com/StanfordBioinformatics/encode_utils/blob/master/encode_utils/MetaDataRegistration/eu_register.py#L169))

**Comment by emi80** [comment]
Hi all, I just submitted a PR to address this issue. Please let me know if it's fine with you or if I need to do anything else.

Best,
Emilio

**Comment by paul-sud** [comment]
Hi Emilio, thanks for the PR. I'll take a look.
