### ISSUE TITLE
get should have datastore=elasticsearch option

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#5]
connection.get has a hard-wired datastore=database.
I will keep this the default but allow it to be overridden with datastore=elasticsearch

**Comment by nathankw** [comment]
This is no-longer set by default. However, when in submission mode, i.e. ``Connection("prod", submission=True)``, or when getting upload credentials, datastore=database will be used in the query string. This was implemented a couple of releases ago I believe, and is definitely in the latest release 1.5.2.
